# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/TAS5111.xdc

# XDC: new/md_v3.xdc

# XDC: new/AK5394.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ax_pwm_0_1/design_1_ax_pwm_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ax_pwm_0_1 || ORIG_REF_NAME==design_1_ax_pwm_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AK5394_LF398_0_0/design_1_AK5394_LF398_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_AK5394_LF398_0_0 || ORIG_REF_NAME==design_1_AK5394_LF398_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_0 || ORIG_REF_NAME==design_1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps7_0_142M_1/design_1_rst_ps7_0_142M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_142M_1 || ORIG_REF_NAME==design_1_rst_ps7_0_142M_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0_0/design_1_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_0 || ORIG_REF_NAME==design_1_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps7_0_axi_periph_0/design_1_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_lite_wrddr_0_0/design_1_axi_lite_wrddr_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_lite_wrddr_0_0 || ORIG_REF_NAME==design_1_axi_lite_wrddr_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_1_0 || ORIG_REF_NAME==design_1_axi_gpio_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FPGA_PWM_0_0/design_1_FPGA_PWM_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_FPGA_PWM_0_0 || ORIG_REF_NAME==design_1_FPGA_PWM_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_debug_io_0_0/design_1_axi_debug_io_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_debug_io_0_0 || ORIG_REF_NAME==design_1_axi_debug_io_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_DAC7631_0_0/design_1_DAC7631_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_DAC7631_0_0 || ORIG_REF_NAME==design_1_DAC7631_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FreqMeasure_0_0/design_1_FreqMeasure_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_FreqMeasure_0_0 || ORIG_REF_NAME==design_1_FreqMeasure_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_0_0/design_1_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_0 || ORIG_REF_NAME==design_1_xlconcat_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI_SIG_CFG_0_0/design_1_AXI_SIG_CFG_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_AXI_SIG_CFG_0_0 || ORIG_REF_NAME==design_1_AXI_SIG_CFG_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Sensor_0_0/design_1_Sensor_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Sensor_0_0 || ORIG_REF_NAME==design_1_Sensor_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_TAS5111_0_0/design_1_TAS5111_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_TAS5111_0_0 || ORIG_REF_NAME==design_1_TAS5111_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s00_data_fifo_0/design_1_s00_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_s00_data_fifo_0 || ORIG_REF_NAME==design_1_s00_data_fifo_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_1 || ORIG_REF_NAME==design_1_auto_pc_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s01_data_fifo_0/design_1_s01_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_s01_data_fifo_0 || ORIG_REF_NAME==design_1_s01_data_fifo_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_2/design_1_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_2 || ORIG_REF_NAME==design_1_auto_pc_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_m00_data_fifo_0/design_1_m00_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_m00_data_fifo_0 || ORIG_REF_NAME==design_1_m00_data_fifo_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_m01_data_fifo_0/design_1_m01_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_m01_data_fifo_0 || ORIG_REF_NAME==design_1_m01_data_fifo_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_m02_data_fifo_0/design_1_m02_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_m02_data_fifo_0 || ORIG_REF_NAME==design_1_m02_data_fifo_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_m03_data_fifo_0/design_1_m03_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_m03_data_fifo_0 || ORIG_REF_NAME==design_1_m03_data_fifo_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_m04_data_fifo_0/design_1_m04_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_m04_data_fifo_0 || ORIG_REF_NAME==design_1_m04_data_fifo_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_m05_data_fifo_0/design_1_m05_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_m05_data_fifo_0 || ORIG_REF_NAME==design_1_m05_data_fifo_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_m06_data_fifo_0/design_1_m06_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_m06_data_fifo_0 || ORIG_REF_NAME==design_1_m06_data_fifo_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_m07_data_fifo_0/design_1_m07_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_m07_data_fifo_0 || ORIG_REF_NAME==design_1_m07_data_fifo_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_m08_data_fifo_0/design_1_m08_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_m08_data_fifo_0 || ORIG_REF_NAME==design_1_m08_data_fifo_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_m09_data_fifo_0/design_1_m09_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_m09_data_fifo_0 || ORIG_REF_NAME==design_1_m09_data_fifo_0} -quiet] -quiet

# XDC: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_0 || ORIG_REF_NAME==design_1_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_0 || ORIG_REF_NAME==design_1_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_rst_ps7_0_142M_1/design_1_rst_ps7_0_142M_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_142M_1 || ORIG_REF_NAME==design_1_rst_ps7_0_142M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_rst_ps7_0_142M_1/design_1_rst_ps7_0_142M_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_142M_1 || ORIG_REF_NAME==design_1_rst_ps7_0_142M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_1_0 || ORIG_REF_NAME==design_1_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_1_0 || ORIG_REF_NAME==design_1_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_s00_data_fifo_0/design_1_s00_data_fifo_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1_ooc.xdc

# XDC: bd/design_1/ip/design_1_s01_data_fifo_0/design_1_s01_data_fifo_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_pc_2/design_1_auto_pc_2_ooc.xdc

# XDC: bd/design_1/ip/design_1_m00_data_fifo_0/design_1_m00_data_fifo_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_m01_data_fifo_0/design_1_m01_data_fifo_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_m02_data_fifo_0/design_1_m02_data_fifo_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_m03_data_fifo_0/design_1_m03_data_fifo_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_m04_data_fifo_0/design_1_m04_data_fifo_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_m05_data_fifo_0/design_1_m05_data_fifo_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_m06_data_fifo_0/design_1_m06_data_fifo_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_m07_data_fifo_0/design_1_m07_data_fifo_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_m08_data_fifo_0/design_1_m08_data_fifo_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_m09_data_fifo_0/design_1_m09_data_fifo_0_ooc.xdc

# XDC: bd/design_1/design_1_ooc.xdc
